### ISSUE TITLE
Allow to define custom roll icon

### ISSUE THREAD

**Issue by sdenec** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#11]
Allow to define a custom html element to be placed inside the .item-image div to have a more granular control about the displayed roll icon (e. g. change size or color when using font-awesome fonts instead of a static background image).

something like 
```js
const rollIcon = "<i class='fa fa-dice-d20'></i>"
```
to produce
```html
<div class="item-image" style="background-image: url(systems/dnd5e/icons/items/inventory/some-item.jpg)">
  <i class="fa fa-dice-d20"></i>
</div>
```
Without the added html the markup resembles the default 5e system sheet markup and should work with any sheet module.

**Comment by akrigline** [comment]
Coming in 3.0.0
