### ISSUE TITLE
[Bug] Not all "action"-options are shown in Actions Tab

### ISSUE THREAD

**Issue by tagnullde** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#12]
Not all available options are shown in the actions tab.  Some Cantrips or Spells are shown. Some are not.

Actions visible:
![grafik](https://user-images.githubusercontent.com/44159008/108034701-2e2a4880-7036-11eb-8f80-0100c995b217.png)

Spells prepared / Always Prepared:
![grafik](https://user-images.githubusercontent.com/44159008/108034735-3da99180-7036-11eb-8611-94b6f296ca97.png)

As you can see, Mage Hand for example is present, but Prestidigitation is not. Although it's configured the same and both are 1 Action.

Thanks for looking into this.

**Comment by akrigline** [comment]
The actions list is meant to show the things most useful in combat. As such it makes some assumptions:

If a spell does damage, show it.
Optionally is a spell has a duration of 1 minute, show it (e.g. bless, this is a module setting)

There is also an option to limit the actions list to only cantrips which meet the above criteria.

Idk about you, but prestidigitation hasn't come up as something someone uses in combat very much.

**Comment by tagnullde** [comment]
Ok, I understand now what to expect from the module.
One could argue about Hex or Invisibility - but I got your point. 

Thanks for the reply and the module. It's quite handy.

**Comment by akrigline** [comment]
Hex and Invisibility are both excellent points I hadn't considered. Hex in particular is most definitely a "combat" spell. Hmmm. I'll have to think about how best to tell the module to look for those.

In your setup, how do you deal the Hex damage?

**Comment by tagnullde** [comment]
The old-school way. Remember (via status icon) that the warlock hex'd someone roll 1d6 manually - apply damage manually.
This is due to the fact the warlock hasn't used this spell as of yet there was no pressure on my end to automate that. ;)
Sorry, for not being of any help with that answer. 

6 hours ago I would have suggested an option the let the player choose what's important to them. But that's not the goal of this project. So I am a bit lost here too. ;)

**Comment by akrigline** [comment]
> 6 hours ago I would have suggested an option the let the player choose what's important to them. But that's not the goal of this project. So I am a bit lost here too. ;)

With the "Favorites Tab" module having been abandoned, I'm actually talking with sdenec about how we might merge his favorites logic into this module. So this isn't super far fetched. I haven't committed fully but every edge case like this pushes me a little farther. You have been helpful!

**Comment by tagnullde** [comment]
You are welcome then. :)
