### ISSUE TITLE
Parse Equipment for Action

### ISSUE THREAD

**Issue by naesean** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#14]
I am trying to configure a shield to have the [Shield Bash variant rule](https://www.dandwiki.com/wiki/Shield_Bashing_(5e_Variant_Rule)). I have it set up with an action

![image](https://user-images.githubusercontent.com/49377730/109583675-1f6f7700-7ab5-11eb-8301-5d855ddb653e.png)

but it doesn't show up in the Actions list.

![image](https://user-images.githubusercontent.com/49377730/109583725-344c0a80-7ab5-11eb-8915-bf0d2649330e.png)

**Comment by akrigline** [comment]
Interesting. What kind of item is this? From what you're showing it should show up if it's a weapon type. If it's not a weapon, that's probably an oversight on my part which could be rectified. Thanks for the report!

**Comment by naesean** [comment]
@akrigline it is an Equipment type. I found the line of code where you are filtering to only 'weapon' type, so it's not really a bug.

Equipment can also be configured to have an attack, as I've shown above. I couldn't really see anything in the code that would break if you included equipment in your filter. Obviously, the proof will be in the testing :)

**Comment by akrigline** [comment]
> @akrigline it is an Equipment type. I found the line of code where you are filtering to only 'weapon' type, so it's not really a bug.
> 
> Equipment can also be configured to have an attack, as I've shown above. I couldn't really see anything in the code that would break if you included equipment in your filter. Obviously, the proof will be in the testing :)

Gotchya, I couldn't remember if I had that or not, thanks for looking.

I'll try to get a fix out for this soon, if you wanna make a PR to that effect I'd be happy to merge it :).

**Comment by naesean** [comment]
Well... I don't have a development environment where I could test to see if it works. I'm happy to make the change in the PR, if you want to test it.

**Comment by naesean** [comment]
Do you prefer PRs off of branches instead of main?

**Comment by akrigline** [comment]
> Do you prefer PRs off of branches instead of main?

Or into main works great. I can test it sure, thanks!

**Comment by akrigline** [comment]
Resolved with #15
