### ISSUE TITLE
Respect Other Player Permissions

### ISSUE THREAD

**Issue by ianm32** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#19]
When other players are allowed to be Observers of a character sheet, the Actions section allows observing players to click on the roll icon for an action, which shows up in the chat as being rolled by the owner player.  This is not possible in other sections of the character sheet, for example the inventory.

**Comment by akrigline** [comment]
Ooof, yeah that's no good. Thanks for the report I'll see what we can do about that.
