### ISSUE TITLE
0.8.6 Accessing the module api on global is depreciated and will be removed in a future update

### ISSUE THREAD

**Issue by Brimcon** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#22]
Getting a Warning when opening a character sheet.
![image](https://user-images.githubusercontent.com/7198283/120248328-8541db00-c22b-11eb-84ef-a7c471b6cf2a.png)

**Comment by akrigline** [comment]
What actor sheet module are you using? I don't get this warning with only the Actions List active while opening the core sheet. I think this is a problem with an integration.

**Comment by Brimcon** [comment]
Tidy5e. Still occurs with Tidy5e Sheet 0.5.4 and Character Actions List 4.1.0

**Comment by akrigline** [comment]
That would be an issue that tidy sheet needs to fix then. Can you open an issue in their repo?
