### ISSUE TITLE
Expose the getActorActionsData function.

### ISSUE THREAD

**Issue by benbarbour** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#23]
This would allow other modules, like token-action-hud, to use your sorting algorithm while controlling their own rendering.

**Comment by akrigline** [comment]
Oh that's a great idea, I'll happily put that method as well as `isItemInActionList ` onto the module api. Though token-action-hud does a lot to be compatible with other systems, so making this one a dependency of it might not go so well.

**Comment by benbarbour** [comment]
Yeah, I think it would have to be a soft dependency.

**Comment by benbarbour** [comment]
Another thing token action HUD would want is subcategories to group by (weapons, consumables, spells by level), etc. I'm not sure whether that level of detail is appropriate for this module or not though.

**Comment by akrigline** [comment]
Subcategories wouldn't be something this module's methods care about, so I'd leave that up to the consumer. Since they'll have all of the items sorted by action type, categorizing those further shouldn't be terribly difficult.
