### ISSUE TITLE
Equipment with Action Type = "None" shouldn't show up in "Special Actions" list

### ISSUE THREAD

**Issue by benbarbour** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#24]
It took me a while to figure out why my item that used zero actions of type "None" was showing up. In my opinion, of course. Maybe also items with a 0 value for the number of actions they use should be omitted from everything?

**Comment by akrigline** [comment]
Can you show me an example of the configuration you are using for this?

I don't tend to think of setting "none" for my items that can't be used, I usually leave it blank. For the "none" in the action type I typically think that means "this item has an effect but does not cost anything to use it"

**Comment by benbarbour** [comment]
It was the robe on the starter hero sorcerer for some reason. I don't think it had any other effects, but I'm not at my computer right now.

**Comment by akrigline** [comment]
Resolved in 4.1.0
