### ISSUE TITLE
Add options to show Legendary, Crew, and Lair actions in their own groups.

### ISSUE THREAD

**Issue by benbarbour** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#25]
Right now Legendary Actions and Lair actions both show up under the "Other" heading on the actions sheet. It would be nice to have the option to separate them out into their own categories, like Crew actions.

**Comment by akrigline** [comment]
Can you clarify what specifically you are "feature requesting" for me?

**Comment by benbarbour** [comment]
Sorry. I've updated the description and first comment for clarity.
