### ISSUE TITLE
dndbeyond NPC sheet affects font and layout of Character Action List

### ISSUE THREAD

**Issue by Brimcon** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#26]
I'm not sure if its the NPC sheet or the Action list Module but with both enabled the action list looks like this:
![image](https://user-images.githubusercontent.com/7198283/121815429-5bc18000-cc2b-11eb-89c1-2ac0be2f863c.png)

**Comment by akrigline** [comment]
Yeah that sounds like something the dndbeyond sheet is doing.

Without looking too close, I'm guessing there's nothing that I can do on the actions list side as the actions list is designed to be styled by other modules.

Maybe open an issue in their repo to ensure that this styling is intentional?

**Comment by Brimcon** [comment]
Whats interesting is that it infects other character sheets. I wasn't sure if it was your end or theirs, so I'll go poke their end.

**Comment by Brimcon** [comment]
Fixed over in dndbeyond NPC sheet!
