### ISSUE TITLE
A way to distinguish spells from cantrips

### ISSUE THREAD

**Issue by cstby** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#34]
First, this module is amazing. I'm designing a one-shot experience for folks who are new to D&D and foundry, and this really helps make character sheets more accessible.

I'm wondering what you'd think about providing some way for players to discern spells from cantrips on the action sheet. I imagine it could work to add another column that displays the spell level.

**Comment by akrigline** [comment]
Thanks for the feedback!

I agree it would be nice to see the level/preparation type (at will for instance) on spells.
I think there might be room for a `small` element below the name itself, rather than a whole new column.

**Comment by akrigline** [comment]
I've added an indicator below the item name with v4.4.0, as well as implemented some sorting logic that makes spellcasters using this much less awful.

![image](https://user-images.githubusercontent.com/7644614/152653707-b3001553-b96d-4cca-9643-08d64603029e.png)
