### ISSUE TITLE
No valid manifest file?

### ISSUE THREAD

**Issue by Enkrod** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#35]
`Error: The request to https://github.com/ElfFriend-DnD/foundryvtt-dnd5eCharacterActions/releases/download//module.json did not provide a valid manifest file.
`

Foundry Link should point to: **https://github.com/ElfFriend-DnD/foundryvtt-dnd5eCharacterActions/releases/download/v4.4.0/module.json**, it can be installed from there.

**Comment by akrigline** [comment]
Thanks for the report, fixed.
