### ISSUE TITLE
Latest release 6.0.3 is actually still 6.0.1

### ISSUE THREAD

**Issue by rikmarais** [ElfFriend-DnD/foundryvtt-dnd5eCharacterActions#53]
![image](https://user-images.githubusercontent.com/34374883/217920529-433969ee-c24f-4f1d-87e7-65f455e8f8cd.png)
Looks like an error in the module.json and the version is still `6.0.1`. This can cause cause issues with updating

Might need a re-release! :)

**Comment by akrigline** [comment]
bizarre, thanks for pointing that out

**Comment by akrigline** [comment]
Alright i think i hit all the right bells and whistles for 6.0.4
this is what I get for not touching this package for so long
